#!/bin/bash

cabal sandbox init
cabal clean
cabal install -j --only-dependencies
cabal build

mkdir target
tar czf target/aemo-archiver-`date +%Y-%m-%d-%H%M%S`.tar.gz \
  dist/build/AEMO-archiver/AEMO-archiver \
  dist/build/initDB/initDB \
  createdb \
  registrations \
  power_station_metadata
