#!/bin/bash

# Since AEMO will not give us a list of power station locations, use the
# Geoscience Australia list to try to work out where the AEMO registered generators are.
#
# This script does the following things:
#   Download the AEMO Registration and Exemption list for the NEM, and extract the Generators list.
#   Download the Geoscience Australia list of power stations and extract the locations.
#   Run the Java tool that tries to match up AEMO stations with GA locations, or else uses a manual match.
#
# Dependencies:
#   curl
#   perl (simpler tools like sed have different command line switches between GNU/Linux and BSD/OSX)
#   Gnumeric
#   xsltproc
#   Java 7 JDK

# All intermediate and final data ends up in here:
PSDIR='power_station_metadata'
MANUAL_LOCATIONS='manual_station_locations.csv'
POWER_STATION_LOCATIONS_CSV='power_station_locations.csv'


# Where to get the URL of the file from
BASE_URL='http://www.aemo.com.au/About-the-Industry/Registration/Current-Registration-and-Exemption-lists'
# What to name the file when downloaded
EXCEL_FILE_NAME="${PSDIR}/Registration_and_Exemption_List.xls"
# Grab the URL of the file out of the HTML, convert spaces to %20
echo "Finding the URL of the AEMO Registration_and_Exemption_List"
FILE_PART_URL=$(curl --silent "${BASE_URL}" | perl -ne '/a href="(.+)">NEM Registration and Exemption List</ && print $1' | perl -pe 's/ /%20/g')

echo "Getting the actual list"
curl --silent -o "${EXCEL_FILE_NAME}" "${BASE_URL}/${FILE_PART_URL}"
echo "Export each sheet to a CSV file"
ssconvert --export-file-per-sheet "${EXCEL_FILE_NAME}" "${PSDIR}/nem-%s.csv"

# The interesting output file should be called 'nem-Generators and Scheduled Loads.csv' (unless they've changed the spreadsheet).
AEMO_GENS_LOADS='nem-Generators and Scheduled Loads.csv'


# The Geoscience Australia ASEIS list of power stations as a WFS service
GA_PS_URL='http://www.ga.gov.au/gis/services/energy/ASEIS_Features/MapServer/WFSServer?service=WFS&request=GetFeature&typeName=energy_ASEIS_Features:Power_Stations&srsName=EPSG:4326&maxFeatures=100000'
# Save the WFS data in here
GA_PS_FILE="${PSDIR}/GA_power_stations.gml"
# XSLT stylesheet to extract power station name and lat/long from the GA WFS data
GA_PS_XSLT="${PSDIR}/GA_power_station_latlong.xsl"
# Put the "name,lat long" data in here
GA_PS_LATLONG='GA_power_station_locations.csv'

echo "Download the Geoscience Australia ASEIS Power Station WFS data"
curl --silent -o "${GA_PS_FILE}" "${GA_PS_URL}"
echo "Extract the names and lat/longs using XSLT"
xsltproc "${GA_PS_XSLT}" "${GA_PS_FILE}" > "${PSDIR}/${GA_PS_LATLONG}"


echo "Compile and run the Java location matcher"
cd "${PSDIR}" \
    && javac PowerStationMatcher.java \
    && java PowerStationMatcher "${MANUAL_LOCATIONS}" "${AEMO_GENS_LOADS}" "${GA_PS_LATLONG}" | sort > "${POWER_STATION_LOCATIONS_CSV}"
cd -

echo "Power stations with locations: "
wc -l ${PSDIR}/${POWER_STATION_LOCATIONS_CSV}
