#!/bin/bash

# Since AEMO will not give us a list of power station locations, use the
# Geoscience Australia list to try to work out where the AEMO registered generators are.

# All intermediate and final data ends up in here:
PSDIR='power_station_metadata'
POWER_STATION_LOCATIONS_CSV="${PSDIR}/power_station_locations.csv"

# Download the AEMO Registration and Exemption list for the NEM, and extract the Generators list.
#
# Dependencies:
#   curl
#   perl (simpler tools like sed have different command line switches between GNU/Linux and BSD/OSX)
#   Gnumeric

# Where to get the URL of the file from
BASE_URL='http://www.aemo.com.au/About-the-Industry/Registration/Current-Registration-and-Exemption-lists'
# What to name the file when downloaded
EXCEL_FILE_NAME="${PSDIR}/Registration_and_Exemption_List.xls"
# Grab the URL of the file out of the HTML, convert spaces to %20
FILE_PART_URL=$(curl --silent ${BASE_URL} | perl -ne '/a href="(.+)">Registration and Exemption List</ && print $1' | perl -pe 's/ /%20/g')

# Get the file
curl --silent -o ${EXCEL_FILE_NAME} "${BASE_URL}/${FILE_PART_URL}"
# Export each sheet to a CSV file
ssconvert --export-file-per-sheet ${EXCEL_FILE_NAME} "${PSDIR}/nem-%s.csv"

# The interesting output file should be called 'nem-Generators and Scheduled Loads.csv' (unless they've changed the spreadsheet).


# Download the Geoscience Australia list of power stations and extract the locations.
#
# Dependencies:
#   curl
#   xsltproc

# The Geoscience Australia ASEIS list of power stations as a WFS service
GA_PS_URL='http://www.ga.gov.au/gis/services/energy/ASEIS_Features/MapServer/WFSServer?service=WFS&request=GetFeature&typeName=energy_ASEIS_Features:Power_Stations&srsName=EPSG:4326&maxFeatures=100000'
# Save the WFS data in here
GA_PS_FILE="${PSDIR}/GA_power_stations.gml"
# XSLT stylesheet to extract power station name and lat/long from the GA WFS data
GA_PS_XSLT="${PSDIR}/GA_power_station_latlong.xsl"
# Put the "name,lat long" data in here
GA_PS_LATLONG="${PSDIR}/GA_power_station_locations.csv"

# Download the GA WFS data
curl --silent -o ${GA_PS_FILE} "${GA_PS_URL}"
# Extract the names and lat/longs
xsltproc ${GA_PS_XSLT} ${GA_PS_FILE} > ${GA_PS_LATLONG}
