aemoDryRun: false
aemoDB:
  dbConnections: 2
  dbConnString: host=192.168.50.4 dbname=aemoarchiver user=aemoarchiver password=weakpass port=5432
aemoUpdateStations: false
aemoStationLocs: power_station_metadata/power_station_locations.csv
aemoGensAndLoads: power_station_metadata/nem-Generators and Scheduled Loads.csv
