db-conn-string: ''
stations-csv: power_station_metadata/power_station_locations.csv
update-stations: false
dry-run: false
db-connections: 10
generators-csv: power_station_metadata/nem-Generators and Scheduled Loads.csv
